function ChannelShiftGUI()
%ChannelShiftGUI  Greates the GUI, sets callback functions. R2015b
%
% Kyle Marchuk, PhD
% Biological Imaging Development Center at UCSF
% June 2017
    %% Create the Figure
    figWidth = 1400;
    figHeight = 900;
    
    % set the display position for the GUI
    displayPos = get(0,'MonitorPositions');
    
    if displayPos(1,2) > 0
        figPos = [...
            (displayPos(1,3) - figWidth)/2,...
            (displayPos(1,4) - figHeight)/2,...
            figWidth,figHeight];
    else
        figPos = [...
            (displayPos(2,3) -figWidth)/2,...
            (displayPos(2,4) - figHeight)/2,...
            figWidth,figHeight];
    end % if
    
    guiCS = figure(...
        'Color',[0.1 0.1 0.44],...
        'Colormap',gray(256),...
        'MenuBar','None',...
        'Name','Channel Shift and Crop',...
        'NumberTitle','Off',...
        'Position',figPos,...
        'Resize','Off',...
        'Tag','guiNC');
    
    %% Create a structure for the parameters and save it as appdata
    % This structure contains the defaults for the GUI. You can edit it
    % here to adapts the default GUI setting to match your preferences. As
    % users edit the parameters in the GUI, these values are updated. It
    % can also be used to store parameters that you do not want users to
    % edit

    structParameters = struct(...
        'pathDir','',...
        'paddingPix',10,...
        'xShift',0,...
        'yShift',0,...
        'zShift',0,...
        'xMin',0,...
        'xMax',0,...
        'yMin',0,...
        'yMax',0,...
        'zMin',0,...
        'zMax',0,...
        'xcMin',1,...
        'xcMax',2,...
        'ycMin',1,...
        'ycMax',2,...
        'zcMin',1,...
        'zcMax',2,...
        'Ch0ContrastValue',0.5,...
        'ChXContrastValue',0.5);
    structParameters.fileNames{1} = '';
    structParameters.fileNames{2} = '';
    structParameters.fileNames{3} = '';
    structParameters.fileNames{4} = '';
    structParameters.fileNames{5} = '';
    structParameters.fileNames{6} = '';
    % Create the axes for the MIPs and assign to parameters
    axes1 = axes('Parent',guiCS,'Units','pixels','Position',[550 485 594 338]);
    axes2 = axes('Parent',guiCS,'Units','pixels','Position',[550 335 594 99]);
    axes3 = axes('Parent',guiCS,'Units','pixels','Position',[1200 485 99 338]);
    structParameters.axes1 = axes1;
    structParameters.axes2 = axes2;
    structParameters.axes3 = axes3;
    setappdata(guiCS,'structParameters',structParameters);
    % Format the MIPs axis
    ylabel(axes1,'Pixels (y)');
    title(axes1,'MIP xy','Color','w','FontSize',14);
    set(axes1,'YColor',[1 1 1],'XColor',[1 1 1]);
    set(axes1,'Color',[0.1 0.1 0.44]);
    axis tight
    xlabel(axes2,'Pixels (x)');
    ylabel(axes2,'Pixels (z)');
    title(axes2,'MIP xz','Color','w','FontSize',14);
    set(axes2,'YColor',[1 1 1],'XColor',[1 1 1]);
    set(axes2,'Color',[0.1 0.1 0.44]);
    set(axes2,'YDir','normal');
    axis tight
    xlabel(axes3,'Pixels (z)');
    ylabel(axes3,'Pixels (y)');
    title(axes3,'MIP yz','Color','w','FontSize',14);
    set(axes3,'YColor',[1 1 1],'XColor',[1 1 1]);
    set(axes3,'Color',[0.1 0.1 0.44]);
    set(axes3,'YDir','reverse');
    set(axes3,'XDir','reverse');
    set(axes3,'YAxisLocation','right');
    axis tight
   
    %% Offset Parameters Preload
    structOffset = struct;
    structOffset.ch1.x = int16(0); 
    structOffset.ch1.y = int16(0);
    structOffset.ch1.z = int16(0);
    structOffset.ch2.x = int16(0); 
    structOffset.ch2.y = int16(0);
    structOffset.ch2.z = int16(0);
    structOffset.ch3.x = int16(0); 
    structOffset.ch3.y = int16(0);
    structOffset.ch3.z = int16(0);
    structOffset.ch4.x = int16(0); 
    structOffset.ch4.y = int16(0);
    structOffset.ch4.z = int16(0);
    structOffset.ch5.x = int16(0); 
    structOffset.ch5.y = int16(0);
    structOffset.ch5.z = int16(0);
    setappdata(guiCS,'structOffset',structOffset);
    
    %% Load Files
    % Ch0
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',12,...
        'Foreground','w',...
        'HorizontalAlign','Left',...
        'Parent',guiCS,...
        'Position',[20 810 200 30],...
        'Style','text',...
        'String','Select ch0 .tif:',...
        'Tag','textCh0File');
    
    handles.displaych0Name = uicontrol(...
        'Background',[0.53 0.80 0.98],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'HorizontalAlign','Left',...
        'Parent',guiCS,...
        'Position',[20 790 400 30],...
        'String',structParameters.fileNames{1},...
        'Style','text',...
        'Tag','displaych0Name');
    
    uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Callback',{@pushFilecallback,guiCS,handles},...
        'FontSize',10,...
        'Parent',guiCS,...
        'Position',[425 790 20 20],...
        'String','...',...
        'Style','pushbutton',...
        'Tag','1',...
        'Tooltipstring','Find the ch0 .tif');
    % Ch1
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',12,...
        'Foreground','w',...
        'HorizontalAlign','Left',...
        'Parent',guiCS,...
        'Position',[20 750 200 30],...
        'Style','text',...
        'String','Select ch1 .tif:',...
        'Tag','textCh1File');
    
    handles.displaych1Name = uicontrol(...
        'Background',[0.53 0.80 0.98],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'HorizontalAlign','Left',...
        'Parent',guiCS,...
        'Position',[20 730 400 30],...
        'String',structParameters.fileNames{2},...
        'Style','text',...
        'Tag','displaych1Name');
    
    uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Callback',{@pushFilecallback,guiCS,handles},...
        'FontSize',10,...
        'Parent',guiCS,...
        'Position',[425 730 20 20],...
        'String','...',...
        'Style','pushbutton',...
        'Tag','2',...
        'Tooltipstring','Find the ch1 .tif');
    % Ch2
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',12,...
        'Foreground','w',...
        'HorizontalAlign','Left',...
        'Parent',guiCS,...
        'Position',[20 690 200 30],...
        'Style','text',...
        'String','Select ch2 .tif:',...
        'Tag','textCh2File');
    
    handles.displaych2Name = uicontrol(...
        'Background',[0.53 0.80 0.98],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'HorizontalAlign','Left',...
        'Parent',guiCS,...
        'Position',[20 670 400 30],...
        'String',structParameters.fileNames{3},...
        'Style','text',...
        'Tag','displaych2Name');
    
    uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Callback',{@pushFilecallback,guiCS,handles},...
        'FontSize',10,...
        'Parent',guiCS,...
        'Position',[425 670 20 20],...
        'String','...',...
        'Style','pushbutton',...
        'Tag','3',...
        'Tooltipstring','Find the ch2 .tif');
    % Ch3
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',12,...
        'Foreground','w',...
        'HorizontalAlign','Left',...
        'Parent',guiCS,...
        'Position',[20 630 200 30],...
        'Style','text',...
        'String','Select ch3 .tif:',...
        'Tag','textCh3File');
    
    handles.displaych3Name = uicontrol(...
        'Background',[0.53 0.80 0.98],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'HorizontalAlign','Left',...
        'Parent',guiCS,...
        'Position',[20 610 400 30],...
        'String',structParameters.fileNames{4},...
        'Style','text',...
        'Tag','displaych3Name');
    
    uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Callback',{@pushFilecallback,guiCS,handles},...
        'FontSize',10,...
        'Parent',guiCS,...
        'Position',[425 610 20 20],...
        'String','...',...
        'Style','pushbutton',...
        'Tag','4',...
        'Tooltipstring','Find the ch3 .tif');
    %Ch4
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',12,...
        'Foreground','w',...
        'HorizontalAlign','Left',...
        'Parent',guiCS,...
        'Position',[20 570 200 30],...
        'Style','text',...
        'String','Select ch4 .tif:',...
        'Tag','textCh4File');
    
    handles.displaych4Name = uicontrol(...
        'Background',[0.53 0.80 0.98],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'HorizontalAlign','Left',...
        'Parent',guiCS,...
        'Position',[20 550 400 30],...
        'String',structParameters.fileNames{5},...
        'Style','text',...
        'Tag','displaych4Name');
    
    uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Callback',{@pushFilecallback,guiCS,handles},...
        'FontSize',10,...
        'Parent',guiCS,...
        'Position',[425 550 20 20],...
        'String','...',...
        'Style','pushbutton',...
        'Tag','5',...
        'Tooltipstring','Find the ch4 .tif');
    %Ch5
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',12,...
        'Foreground','w',...
        'HorizontalAlign','Left',...
        'Parent',guiCS,...
        'Position',[20 510 200 30],...
        'Style','text',...
        'String','Select ch5 .tif:',...
        'Tag','textCh5File');
    
    handles.displaych5Name = uicontrol(...
        'Background',[0.53 0.80 0.98],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'HorizontalAlign','Left',...
        'Parent',guiCS,...
        'Position',[20 490 400 30],...
        'String',structParameters.fileNames{6},...
        'Style','text',...
        'Tag','ddisplaych5Name');
    
    uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Callback',{@pushFilecallback,guiCS,handles},...
        'FontSize',10,...
        'Parent',guiCS,...
        'Position',[425 490 20 20],...
        'String','...',...
        'Style','pushbutton',...
        'Tag','6',...
        'Tooltipstring','Find the ch5 .tif');
    %% Radiobuttons
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',14,...
        'Foreground','w',...
        'Parent',guiCS,...
        'Position',[50 390 305 30],...
        'Style','text',...
        'String','Select Channel to Overlay with Ch0:',...
        'Tag','textSaveSelect')
    
    buttonGroup = uibuttongroup(...
        'Position',[0.038 0.40 0.21 0.04],...
        'Units','Normalized',...
        'BackgroundColor',[0.1 0.1 0.44]);
    set(buttonGroup,'SelectionChangedFcn',{@buttonCallback,guiCS});
    
    uicontrol(...
        'Style','radiobutton',...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Parent',buttonGroup,...
        'Position',[25 5 40 25],...
        'FontSize',10,...
        'Units','Normalized',...
        'String','ch1',...
        'Tag','ch1');
    
    uicontrol(...
        'Style','radiobutton',...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Parent',buttonGroup,...
        'Position',[75 5 40 25],...
        'FontSize',10,...
        'Units','Normalized',...
        'String','ch2',...
        'Tag','ch2');
    
    uicontrol(...
        'Style','radiobutton',...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Parent',buttonGroup,...
        'Position',[125 5 40 25],...
        'FontSize',10,...
        'Units','Normalized',...
        'String','ch3',...
        'Tag','ch3');
    
    uicontrol(...
        'Style','radiobutton',...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Parent',buttonGroup,...
        'Position',[175 5 40 25],...
        'FontSize',10,...
        'Units','Normalized',...
        'String','ch4',...
        'Tag','ch4');
    
    uicontrol(...
        'Style','radiobutton',...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Parent',buttonGroup,...
        'Position',[225 5 40 25],...
        'FontSize',10,...
        'Units','Normalized',...
        'String','ch5',...
        'Tag','ch5');
    
        
    
    
    %% Contrast Sliders
    sliderCh0 = uicontrol(...
        'Background',[1 0 0],...
        'Foreground',[0.1 0.1 0.44],...
        'Callback',{@slidercontrastcallback, guiCS},...
        'Min',0.01,...
        'Max',1,...
        'Parent',guiCS,...
        'Position',[100 325 200 20],...
        'Style','slider',...
        'Tag','sliderCh0',...
        'Value',structParameters.Ch0ContrastValue);
   
    sliderChX = uicontrol(...
        'Background',[0 0.5 0],...
        'Foreground',[0.1 0.1 0.44],...
        'Callback',{@slidercontrastcallback, guiCS},...
        'Min',0.01,...
        'Max',1,...
        'Parent',guiCS,...
        'Position',[100 300 200 20],...
        'Style','slider',...
        'Tag','sliderChX',...
        'Value',structParameters.ChXContrastValue);
    
    %% ROI boxes
    panelDisplay = uipanel(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor','w',...
        'FontSize',12,...
        'BorderType','Line',...
        'HighlightColor',[0.53 0.80 0.98],...
        'Parent',guiCS,...
        'Position',[1185 275 125 160]./[figPos(3) figPos(4) figPos(3) figPos(4)],...
        'Title','Display ROI',...
        'TitlePosition','Centertop',...
        'Tag','panelRun',...
        'Units','Pixels');
    uistack(panelDisplay,'bottom')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelDisplay,...
        'Position',[30 115 30 20],...
        'Style','text',...
        'String','Min',...
        'Tag','textMin')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelDisplay,...
        'Position',[80 115 30 20],...
        'Style','text',...
        'String','Max',...
        'Tag','textMax')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelDisplay,...
        'Position',[10 90 10 20],...
        'Style','text',...
        'String','X',...
        'Tag','textX')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelDisplay,...
        'Position',[10 55 10 20],...
        'Style','text',...
        'String','Y',...
        'Tag','textZ')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelDisplay,...
        'Position',[10 20 10 20],...
        'Style','text',...
        'String','Z',...
        'Tag','textZ')
    
    editXmin = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelDisplay,...
        'Position',[30 90 35 20],...
        'Style','edit',...
        'String',structParameters.xMin,...
        'Tag','editXmin');
    set(editXmin.Handle,'Callback',{@editROIcallback,editXmin,guiCS})
    
    editXmax = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelDisplay,...
        'Position',[80 90 35 20],...
        'Style','edit',...
        'String',structParameters.xMax,...
        'Tag','editXmax');
    set(editXmax.Handle,'Callback',{@editROIcallback,editXmax,guiCS})
    
    editYmin = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelDisplay,...
        'Position',[30 55 35 20],...
        'Style','edit',...
        'String',structParameters.yMin,...
        'Tag','editYmin');
    set(editYmin.Handle,'Callback',{@editROIcallback,editYmin,guiCS})
    
    editYmax = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelDisplay,...
        'Position',[80 55 35 20],...
        'Style','edit',...
        'String',structParameters.yMax,...
        'Tag','editYmax');
    set(editYmax.Handle,'Callback',{@editROIcallback,editYmax,guiCS})
    
    editZmin = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelDisplay,...
        'Position',[30 20 35 20],...
        'Style','edit',...
        'String',structParameters.zMin,...
        'Tag','editZmin');
    set(editZmin.Handle,'Callback',{@editROIcallback,editZmin,guiCS})
    
    editZmax = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelDisplay,...
        'Position',[80 20 35 20],...
        'Style','edit',...
        'String',structParameters.zMax,...
        'Tag','editZmax');
    set(editZmax.Handle,'Callback',{@editROIcallback,editZmax,guiCS})
    
    %% Offset boxes
    panelOffset = uipanel(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor','w',...
        'FontSize',12,...
        'BorderType','Line',...
        'HighlightColor',[0.53 0.80 0.98],...
        'Parent',guiCS,...
        'Position',[600 100 500 160]./[figPos(3) figPos(4) figPos(3) figPos(4)],...
        'Title','Channel Offsets',...
        'TitlePosition','Centertop',...
        'Tag','panelOffset',...
        'Units','Pixels');
    uistack(panelOffset,'bottom')
    % Channel 1
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[45 110 30 20],...
        'Style','text',...
        'String','ch1',...
        'Tag','textch1')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[10 85 30 20],...
        'Style','text',...
        'String','X',...
        'Tag','textX1')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[10 50 30 20],...
        'Style','text',...
        'String','Y',...
        'Tag','textY1')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[10 15 30 20],...
        'Style','text',...
        'String','Z',...
        'Tag','textZ1')
    
    editXoff1 = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelOffset,...
        'Position',[40 85 35 20],...
        'Style','edit',...
        'String',structOffset.ch1.x,...
        'Tag','editXoff1',...
        'TooltipString','Ch1 Offset');
    set(editXoff1.Handle,'Callback',{@editOffsetcallback,editXoff1,guiCS})
    
    editYoff1 = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelOffset,...
        'Position',[40 50 35 20],...
        'Style','edit',...
        'String',structOffset.ch1.y,...
        'Tag','editYoff1',...
        'TooltipString','Ch1 Offset');
    set(editYoff1.Handle,'Callback',{@editOffsetcallback,editYoff1,guiCS})
    
    editZoff1 = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelOffset,...
        'Position',[40 15 35 20],...
        'Style','edit',...
        'String',structOffset.ch1.z,...
        'Tag','editZoff1',...
        'TooltipString','Ch1 Offset');
    set(editZoff1.Handle,'Callback',{@editOffsetcallback,editZoff1,guiCS})
    % Channel 2
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[135 110 30 20],...
        'Style','text',...
        'String','ch2',...
        'Tag','textch2')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[100 85 30 20],...
        'Style','text',...
        'String','X',...
        'Tag','textX2')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[100 50 30 20],...
        'Style','text',...
        'String','Y',...
        'Tag','textY2')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[100 15 30 20],...
        'Style','text',...
        'String','Z',...
        'Tag','textZ2')
    
    editXoff2 = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelOffset,...
        'Position',[130 85 35 20],...
        'Style','edit',...
        'String',structOffset.ch2.x,...
        'Tag','editXoff2',...
        'TooltipString','Ch2 Offset');
    set(editXoff2.Handle,'Callback',{@editOffsetcallback,editXoff2,guiCS})
    
    editYoff2 = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelOffset,...
        'Position',[130 50 35 20],...
        'Style','edit',...
        'String',structOffset.ch2.y,...
        'Tag','editYoff2',...
        'TooltipString','Ch2 Offset');
    set(editYoff2.Handle,'Callback',{@editOffsetcallback,editYoff2,guiCS})
    
    editZoff2 = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelOffset,...
        'Position',[130 15 35 20],...
        'Style','edit',...
        'String',structOffset.ch2.z,...
        'Tag','editZoff2',...
        'TooltipString','Ch2 Offset');
    set(editZoff2.Handle,'Callback',{@editOffsetcallback,editZoff2,guiCS})
    % Channel 3
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[235 110 30 20],...
        'Style','text',...
        'String','ch3',...
        'Tag','textch3')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[200 85 30 20],...
        'Style','text',...
        'String','X',...
        'Tag','textX3')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[200 50 30 20],...
        'Style','text',...
        'String','Y',...
        'Tag','textY3')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[200 15 30 20],...
        'Style','text',...
        'String','Z',...
        'Tag','textZ3')
    
    editXoff3 = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelOffset,...
        'Position',[230 85 35 20],...
        'Style','edit',...
        'String',structOffset.ch3.x,...
        'Tag','editXoff3',...
        'TooltipString','Ch3 Offset');
    set(editXoff3.Handle,'Callback',{@editOffsetcallback,editXoff3,guiCS})
    
    editYoff3 = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelOffset,...
        'Position',[230 50 35 20],...
        'Style','edit',...
        'String',structOffset.ch3.y,...
        'Tag','editYoff3',...
        'TooltipString','Ch3 Offset');
    set(editYoff3.Handle,'Callback',{@editOffsetcallback,editYoff3,guiCS})
    
    editZoff3 = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelOffset,...
        'Position',[230 15 35 20],...
        'Style','edit',...
        'String',structOffset.ch3.z,...
        'Tag','editZoff3',...
        'TooltipString','Ch3 Offset');
    set(editZoff3.Handle,'Callback',{@editOffsetcallback,editZoff3,guiCS})
    % Channel 4
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[335 110 30 20],...
        'Style','text',...
        'String','ch4',...
        'Tag','textch4')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[300 85 30 20],...
        'Style','text',...
        'String','X',...
        'Tag','textX4')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[300 50 30 20],...
        'Style','text',...
        'String','Y',...
        'Tag','textY4')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[300 15 30 20],...
        'Style','text',...
        'String','Z',...
        'Tag','textZ4')
    
    editXoff4 = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelOffset,...
        'Position',[330 85 35 20],...
        'Style','edit',...
        'String',structOffset.ch4.x,...
        'Tag','editXoff4',...
        'TooltipString','Ch4 Offset');
    set(editXoff4.Handle,'Callback',{@editOffsetcallback,editXoff4,guiCS})
    
    editYoff4 = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelOffset,...
        'Position',[330 50 35 20],...
        'Style','edit',...
        'String',structOffset.ch4.y,...
        'Tag','editYoff4',...
        'TooltipString','Ch4 Offset');
    set(editYoff4.Handle,'Callback',{@editOffsetcallback,editYoff4,guiCS})
    
    editZoff4 = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelOffset,...
        'Position',[330 15 35 20],...
        'Style','edit',...
        'String',structOffset.ch4.z,...
        'Tag','editZoff4',...
        'TooltipString','Ch4 Offset');
    set(editZoff4.Handle,'Callback',{@editOffsetcallback,editZoff4,guiCS})
    % Channel 5
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[435 110 30 20],...
        'Style','text',...
        'String','ch5',...
        'Tag','textch5')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[400 85 30 20],...
        'Style','text',...
        'String','X',...
        'Tag','textX5')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[400 50 30 20],...
        'Style','text',...
        'String','Y',...
        'Tag','textY5')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelOffset,...
        'Position',[400 15 30 20],...
        'Style','text',...
        'String','Z',...
        'Tag','textZ5')
    
    editXoff5 = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelOffset,...
        'Position',[430 85 35 20],...
        'Style','edit',...
        'String',structOffset.ch5.x,...
        'Tag','editXoff5',...
        'TooltipString','Ch5 Offset');
    set(editXoff5.Handle,'Callback',{@editOffsetcallback,editXoff5,guiCS})
    
    editYoff5 = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelOffset,...
        'Position',[430 50 35 20],...
        'Style','edit',...
        'String',structOffset.ch5.y,...
        'Tag','editYoff5',...
        'TooltipString','Ch5 Offset');
    set(editYoff5.Handle,'Callback',{@editOffsetcallback,editYoff5,guiCS})
    
    editZoff5 = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelOffset,...
        'Position',[430 15 35 20],...
        'Style','edit',...
        'String',structOffset.ch5.z,...
        'Tag','editZoff5',...
        'TooltipString','Ch5 Offset');
    set(editZoff5.Handle,'Callback',{@editOffsetcallback,editZoff5,guiCS})
    
    %% Crop boxes
    panelCrop = uipanel(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor','w',...
        'FontSize',12,...
        'BorderType','Line',...
        'HighlightColor',[0.53 0.80 0.98],...
        'Parent',guiCS,...
        'Position',[1185 100 125 160]./[figPos(3) figPos(4) figPos(3) figPos(4)],...
        'Title','Crop ROI',...
        'TitlePosition','Centertop',...
        'Tag','panelRun',...
        'Units','Pixels');
    uistack(panelCrop,'bottom')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelCrop,...
        'Position',[30 115 30 20],...
        'Style','text',...
        'String','Min',...
        'Tag','textcMin')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelCrop,...
        'Position',[80 115 30 20],...
        'Style','text',...
        'String','Max',...
        'Tag','textcMax')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelCrop,...
        'Position',[10 90 10 20],...
        'Style','text',...
        'String','X',...
        'Tag','textcX')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelCrop,...
        'Position',[10 55 10 20],...
        'Style','text',...
        'String','Y',...
        'Tag','textcY')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[1 1 1],...
        'Parent',panelCrop,...
        'Position',[10 20 10 20],...
        'Style','text',...
        'String','Z',...
        'Tag','textcZ')
    
    editcXmin = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelCrop,...
        'Position',[30 90 35 20],...
        'Style','edit',...
        'String',structParameters.xcMin,...
        'Tag','editcXmin');
    set(editcXmin.Handle,'Callback',{@editCropcallback,editcXmin,guiCS})
    
    editcXmax = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelCrop,...
        'Position',[80 90 35 20],...
        'Style','edit',...
        'String',structParameters.xcMax,...
        'Tag','editcXmax');
    set(editcXmax.Handle,'Callback',{@editCropcallback,editcXmax,guiCS})
    
    editcYmin = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelCrop,...
        'Position',[30 55 35 20],...
        'Style','edit',...
        'String',structParameters.ycMin,...
        'Tag','editcYmin');
    set(editcYmin.Handle,'Callback',{@editCropcallback,editcYmin,guiCS})
    
    editcYmax = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelCrop,...
        'Position',[80 55 35 20],...
        'Style','edit',...
        'String',structParameters.ycMax,...
        'Tag','editcYmax');
    set(editcYmax.Handle,'Callback',{@editCropcallback,editcYmax,guiCS})
    
    editcZmin = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelCrop,...
        'Position',[30 20 35 20],...
        'Style','edit',...
        'String',structParameters.zcMin,...
        'Tag','editcZmin');
    set(editcZmin.Handle,'Callback',{@editCropcallback,editcZmin,guiCS})
    
    editcZmax = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelCrop,...
        'Position',[80 20 35 20],...
        'Style','edit',...
        'String',structParameters.zcMax,...
        'Tag','editcZmax');
    set(editcZmax.Handle,'Callback',{@editCropcallback,editcZmax,guiCS})
    
    %% Create the Load Button
    uicontrol(...
        'BackgroundColor',[0.53 0.80 0.98],...
        'ForegroundColor',[0.1 0.1 0.44],...
        'Callback',{@pushLoad,guiCS,buttonGroup,panelDisplay},...
        'FontSize',14,...
        'Parent',guiCS,...
        'Position',[165 430 80 40],...
        'String','Load',...
        'Style','pushbutton',...
        'Tag','pushLoad',...
        'TooltipString','Update the shifting display');
    
    %% Create the Crop Button
    uicontrol(...
        'BackgroundColor',[0.53 0.80 0.98],...
        'ForegroundColor',[0.1 0.1 0.44],...
        'Callback',{@pushCrop,guiCS},...
        'FontSize',14,...
        'Parent',guiCS,...
        'Position',[1175 50 150 40],...
        'String','Crop Directory',...
        'Style','pushbutton',...
        'Tag','pushCrop',...
        'TooltipString','Crop the directory using offsets');
    
 
    
    
    
    
    

end % ChannelShiftGUI

